import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/Sidebar/AppSidebar";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import PrivyContainer from "./components/privy-provider";
import AuthButton from "./components/Header/AuthButton";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Lume AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${roboto} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PrivyContainer>
            <SidebarProvider>
              <AppSidebar />
              <main className="w-full dark:bg-[#232227] relative overflow-hidden">
                <div className="absolute flex w-full h-11 justify-between items-center pr-1 backdrop-blur-sm">
                  <SidebarTrigger className="dark:invert" />
                  <AuthButton />
                </div>
                {children}
              </main>
            </SidebarProvider>
          </PrivyContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}
