import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/Sidebar/AppSidebar";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import PrivyContainer from "./components/privy-provider";
import AuthButton from "./components/Header/AuthButton";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Lume AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PrivyContainer>
            <SidebarProvider>
              <AppSidebar />
              <main className="flex flex-col w-full dark:bg-[#232227] relative">
                <div className="flex sticky top-0 z-10 w-full h-11 justify-between items-center pr-1 bg-zinc-200/60 dark:bg-zinc-800/80 border-solid border-b-[1px] border-zinc-300 dark:border-zinc-700">
                  <SidebarTrigger className="dark:invert" />
                  <AuthButton />
                </div>
                <div className="flex-grow relative">{children}</div>
              </main>
            </SidebarProvider>
          </PrivyContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}
